name: Deploy
on:
    workflow_run:
        workflows: ["Docker CI"]
        branches: 
            - development
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Add helm repository to helm
              run: helm repo add kiss-gateway https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/commonground-gateway/main/helm
            - name: Set kubeconfig
              id: kubeconfig
              run: |
                  if [ "${{ secrets.KISS_ACC_KUBECONFIG }}" != "" ]; then
                    printf "${{ secrets.KISS_ACC_KUBECONFIG }}" > kubeconfig.yaml
                    echo "##[set-output name=success]true"
                  else
                    echo "##[set-output name=success]false"
                  fi
            - name: Upgrade helm installation
              if: steps.kubeconfig.outputs.success == 'true' && success()
              run: helm upgrade --install commonground-gateway kiss-frontend/commonground-gateway --reuse-values --kubeconfig="kubeconfig.yaml" --namespace=frontend --description https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/commonground-gateway/main/helm
            - name: Rollout new containers
              if: steps.kubeconfig.outputs.success == 'true' && success()
              run: kubectl rollout restart deployment/kiss-frontend --kubeconfig="kubeconfig.yaml"  --namespace=frontend
            - name: Cleanup
              run: |
                  helm repo remove kiss-frontend
                  rm -rf ~/.helm/cache/archive/*
                  rm -rf ~/.helm/repository/cache/*
